# Generated by Django 2.2.4 on 2019-08-19 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, verbose_name='Имя продавца')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия продовца')),
            ],
            options={
                'verbose_name': 'Фамилия продовца',
                'verbose_name_plural': 'Фамилия продовца',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Под категория')),
            ],
            options={
                'verbose_name': 'Под категорияы',
                'verbose_name_plural': 'Под категория',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Тип')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Тип',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MyShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('product', models.CharField(max_length=40, verbose_name='Продукт')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
                ('image', models.CharField(blank=True, max_length=10, null=True, verbose_name='Путь до изображения')),
                ('specifications', models.TextField(max_length=500, verbose_name='Характеристики')),
                ('about', models.TextField(max_length=500, verbose_name='Об товаре')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Созданно')),
                ('update_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Обновленно')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.Category', verbose_name='Категория')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.SubCategory', verbose_name='Под категория')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.Type', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='LiveSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(max_length=30, verbose_name='Номер продавец')),
                ('sails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.Sails', verbose_name='Данные продовца')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.SubCategory', verbose_name='Под категория'),
        ),
    ]
