# Generated by Django 2.2.4 on 2019-08-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myshop',
            name='availability',
            field=models.BooleanField(default=True, verbose_name='Наличие тавара'),
        ),
        migrations.AlterField(
            model_name='myshop',
            name='about',
            field=models.TextField(max_length=500, null=True, verbose_name='Об товаре'),
        ),
        migrations.AlterField(
            model_name='myshop',
            name='create_time',
            field=models.DateTimeField(db_index=True, verbose_name='Созданно'),
        ),
        migrations.AlterField(
            model_name='myshop',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
    ]
