# Generated by Django 2.2.4 on 2019-08-19 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_category_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.SubCategory', verbose_name='Под категория'),
        ),
    ]
