# Generated by Django 2.2.4 on 2019-08-19 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_subcategory_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.Category', verbose_name='Под категория'),
        ),
    ]
