# Generated by Django 2.2.4 on 2019-08-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190819_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='myshop',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='myshop',
            name='availability',
            field=models.BooleanField(blank=True, default=True, verbose_name='Наличие тавара'),
        ),
        migrations.AlterField(
            model_name='myshop',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Созданно'),
        ),
        migrations.AlterField(
            model_name='myshop',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='myshop',
            name='specifications',
            field=models.TextField(blank=True, max_length=500, verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='myshop',
            name='update_time',
            field=models.DateTimeField(db_index=True, verbose_name='Обновленно'),
        ),
    ]
