# Generated by Django 2.2.4 on 2019-08-19 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190819_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myshop',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='myshop',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.SubCategory', verbose_name='Под категория'),
        ),
        migrations.AlterField(
            model_name='myshop',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.Type', verbose_name='Тип'),
        ),
    ]
