# Generated by Django 2.2.4 on 2019-08-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20190819_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='myshop',
            name='discount_bool',
            field=models.BooleanField(blank=True, default=False, verbose_name='Активна ли скидка!'),
        ),
        migrations.AddField(
            model_name='myshop',
            name='hot_sale',
            field=models.BooleanField(blank=True, default=False, verbose_name='Товар дня'),
        ),
    ]
