# Generated by Django 2.2.4 on 2019-08-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20190823_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myshop',
            name='specifications',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Характеристики'),
        ),
    ]
